version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/circle_test
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    external_links:
      - psql
    entrypoint: dockerize -wait tcp://db:5432
    extra_hosts:
      -"db:0.0.0.0"
