name: cas
dependencies:
- libgfortran=1.0=0
- mkl=11.3.1=0
- numpy=1.10.4=py35_0
- openblas=0.2.14=3
- pip=8.1.0=py35_0
- python=3.5.0=1
- readline=6.2=2
- scipy=0.17.0=np110py35_1
- setuptools=20.2.2=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - astroid==1.4.4
  - behave==1.2.5
  - colorama==0.3.6
  - dj-database-url==0.4.0
  - dj-static==0.0.6
  - django==1.9.2
  - django-debug-toolbar==1.4
  - django-filter==0.12.0
  - django-nose==1.4.3
  - django-toolbelt==0.0.1
  - djangorestframework==3.3.2
  - gunicorn==19.4.5
  - lazy-object-proxy==1.2.1
  - markdown==2.6.5
  - nose==1.3.7
  - parse==1.6.6
  - parse-type==0.3.4
  - psycopg2==2.6.1
  - pylint==1.5.4
  - pylint-django==0.7.1
  - pylint-plugin-utils==0.2.3
  - six==1.10.0
  - sqlparse==0.1.18
  - static3==0.6.1
  - whitenoise==2.0.6
  - wrapt==1.10.6
